-- Registra eventos da Stripe para impedir processamento duplicado.
-- O endpoint usa esta tabela antes de atualizar public.profiles.

CREATE TABLE IF NOT EXISTS public.stripe_webhook_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id TEXT NOT NULL UNIQUE,
  event_type TEXT,
  status TEXT,
  customer_email TEXT,
  payload JSONB,
  created_at TIMESTAMPTZ DEFAULT now(),
  processed_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.stripe_webhook_events ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS stripe_webhook_events_created_at_idx
  ON public.stripe_webhook_events (created_at DESC);
